### PR TITLE
Test all components "branch".

### PR DESCRIPTION
**Pull request by MarcoAurelioAntonio**
## Dear Reviewer Hi, 
in this PR I made the following features and functionalities of the requirements:

### Home page

- When the page loads, the webapp shows the list of categories that could be filtered out by some parameter, for example by the category name.
    - Along with the category name, you will display some numeric values per category that come from the API.
    - When the user clicks (or taps) on a category item, the application navigates to the details page.
    
### Details page

- In the details page, the webapp retrieves data from the API to show detailed data in the category.
- When the user clicks on the "Back" button (<), the user navigates to the home page.

### Technical requirements

- The project is a single-page application (SPA) built with React and Redux.
- The data retrieved from the API should be stored in the Redux store.
- You should filter the data that you retrieve from the API using a Filter stateless component.
- Every page (the main page and the pages for each item) should have a unique route within the SPA.
- The project should be deployed and accessible online (add a link to the online version of your app to your README file).

### CODE REVIEW

**Review by DeliceLydia — CHANGES_REQUESTED** [review]
## Hi @MarcoAurelioAntonio, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


 ## Required Changes ♻️
- [x] As requested by the previous reviewer you should record a video presenting the features of the project, remember to add it to the README
- [x] I am not able to navigate the detail page by clicking the individual crypto item, please work on that and remember to add a link from the `Detail` page to the `Home` page by clicking the "Back" button


### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MarcoAurelioAntonio** [comment]
Hi @DeliceLydia !...

Regarding `I am not able to navigate the detail page by clicking the individual crypto item, please work on that and remember to add a link from the Detail page to the Home page by clicking the "Back" button.`

The link **is in the icon** of every card item... I notice that could be a problem, so I add a right arrow next to every icon, but that feature is not deployed because is in this PR and Netlify runs from `dev`.

This is from `test` : 
https://deploy-preview-6--hilarious-buttercream-5cfeaa.netlify.app/

Kindly take a look if everything is ok, and meanwhile, I'm going to make the required video.

Thanks!!

**Review by BertrandConxy — CHANGES_REQUESTED** [review]
Hi @MarcoAurelioAntonio 

Good job so far! 👏 👏 
There are some issues that you still need to work on to go to the next project but you are almost there! 🏃‍♂️ 🏃‍♂️ 


## Highlights 💪 
- No linter errors
- Good improvements
- correct flow is used
- good PR

## Required Changes ♻️

- [ ] It looks like the suggested improvement of Recording a video presenting your project and then adding the link in the README file has not been implemented. Currently, your README file on the `test` branch which you have requested the review, contains irrelevant information compared to this capstone. Please take a look at the screenshot below 👇 
image

So please as suggested by the previous reviewer, add the video link to your README but I would also strongly suggest that you update the entire README file on this current branch (`test`) by following the template given by Microverse. I hope that you are familiar with it 😉 

**NOTE** You **may or may have a good README on the dev branch. What we care about is what changes or data you have on the current branch from which you have requested a review**. It is your **duty to keep your current branch synced with the default or the base branch** 😎 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by mirouhml — APPROVED** [review]
# APPROVED 🟢

Hi @MarcoAurelioAntonio, 

Your React capstone project is complete, I love it!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights

- Great job setting up the correct linters ✔️
- Highly organized and clean code ✔️ 👨🏻‍💻
- Professional documentation ✔️
- Correct workflow ✔️
- Meaningful commit messages ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ ] **Your website is almost perfect it just needs one more thing to change, the title is currently still this:**
  image
  **I recommend you change that by going to `public/index.html`, you'll find `title` there and `description`, adjust them to what suits your project!**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
